### ISSUE TITLE
Sea Block compatibility

### ISSUE THREAD

**Issue by KiwiHawk** [kirazy/reskins-compatibility#1]
Sea block changes the recipe for several buildings. When Sea Block is enabled, can you show these as a different tier?

- Algae farm 3: T4 > T3
- Filtration unit 1: T2 > T1
- Crystallizer 1: T2 > T1

![image](https://user-images.githubusercontent.com/59639/122657085-65f7f700-d1b4-11eb-9578-a2ac295e80c1.png)
![image](https://user-images.githubusercontent.com/59639/122657095-760fd680-d1b4-11eb-92a7-5f0108797b95.png)
![image](https://user-images.githubusercontent.com/59639/122657104-832cc580-d1b4-11eb-8d42-acec205c4629.png)

**Comment by kirazy** [comment]
Is this Sea Block as it is currently release, or Sea Block as it will be released shortly?

**Comment by KiwiHawk** [comment]
Filtration unit and Crystallizer are the same. This is the current Algae farm 3 recipe:

![image](https://user-images.githubusercontent.com/59639/122658348-3bac3680-d1c0-11eb-8e24-883332bc48fe.png)

**Comment by kirazy** [comment]
Commit kirazy/reskins-angels@2a401e0479ecb90596bf38dd0fa39cbec85cd754 fixes this.

**Comment by KiwiHawk** [comment]
Found one more, sorry! Chemical plant 1 needs to go from T2 down to T1.

![image](https://user-images.githubusercontent.com/59639/125415976-811de001-faae-4c82-a5af-520a0a27a686.png)

**Comment by KiwiHawk** [comment]
Adding so it's logged:

Plasma Turret 1 takes red circuits, should be T3.
Plasma Turret 2 takes blue circuits, should be T4.

Higher tiers of plasma turrets are hidden.

All this in Sea Block 0.5.5

**Comment by kirazy** [comment]
Was there something that was still needed for this, Kiwi?

**Comment by KiwiHawk** [comment]
Nope, all looks good from a Sea Block perspective!
