### ISSUE TITLE
Incompatible with latest Black Rubber Belts

### ISSUE THREAD

**Issue by rafasoares** [kirazy/reskins-compatibility#6]
Deadlock added the belt icons with different materials and removed the base one, so you need to update this line:

https://github.com/kirazy/reskins-compatibility/blob/f962d02625f0df14da8d614a601251b51ba8a802/prototypes/mods/deadlockblackrubberbelts.lua#L42

With:

```lua
icon = actions.icons_path.."/rubber-belt-iron.png",
-- or
icon = actions.icons_path.."/rubber-belt-steel.png",
```

Or you can change the material based on the tier :)

**Comment by kirazy** [comment]
Oh, this was resolved a while ago. Commit d1a4d334fde4661af53646c46ad5b6aa01be4f21 resolved this.
