### ISSUE TITLE
Error displaying the conveyor texture on the ground or conveyor belt

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [kirazy/reskins-compatibility#7]
I had a mod installed Black Rubber Belt after a while decided to add "Bob's Logistics" and your mod "Artisanal Reskins: Bob's Mods" to it during the game I noticed that the conveys that lie on the lemle as objects and, accordingly, those that are transported along the tape are displayed with an error:

![image](https://github.com/kirazy/reskins-compatibility/assets/46845681/8517bb02-4cc7-4d9c-9ff8-87d3ff7671eb)

**Comment by kirazy** [comment]
Update to 2.1.9 and you're good to go. :)
